name: Task
description: Create a new to-do card for your Spark project
title: "[TASK] "
labels: ["help wanted"]
assignees:
  - ""
body:
  - type: markdown
    attributes:
      value: |
        **Describe the task**: What needs to be done?
  - type: input
    id: project
    attributes:
      label: Project
      description: "Select your project"
      required: true
  - type: input
    id: due-date
    attributes:
      label: Due Date
      description: YYYY-MM-DD
      required: false
